### ISSUE TITLE
General object layout to be adapted?

### ISSUE THREAD

**Issue by rajanski** [oadam/proprio#20]
Hi I was just wondering, because in reality,

- A tenant can rent more than one property
- A property has a rent price (a rent revision in your code afaiu)

So should'nt rent_revisions be attached to properties?

**Comment by oadam** [comment]
Hi,  There are 2 points here :

- property has a fixed rent price. Might be true in your case, but I think having 1 price per tenancy is more general. For example, some tenants negociate their rent....

- tenants can rent more than 1 property. That is true. The link between tenant and property could become a N-N relationship via the creation of a new `Tenancy` object. All objects that are currently attached to the tenant (rentrevision, fees, payments...) would be attached to the `Tenancy` object.
Unfortunately that would require many changes in the code and most importantly it would complicate the UI a lot for the simple use case where tenants only rent 1 property. I don't think that is something that I want to integrate.
A work around for the "1 tenant - n properties" use case would be to duplicate tenants (1 copy per property)...
